import { VerticalBox } from "std-widgets.slint";
import { Header } from "header.slint";

export component Content {
    padding: 0;
    Rectangle {
        padding: 0;
        background: #121C22;
        VerticalBox {
            padding: 0;
            Header {
                Width: root.width;
            }

            Text {
                padding: 0;
                text: "some";
                color: red;
            }
        }
    }
}
