import { VerticalBox } from "std-widgets.slint";

global ActivePath {
    out property <string> name;
}

global Icons {
    in property <[image]> top_btns: [
        @image-url("../assets/sidebar/heroicons--book-open.svg"),
        @image-url("../assets/sidebar/heroicons--folder.svg"),
        @image-url("../assets/sidebar/heroicons--clock.svg"),
        @image-url("../assets/sidebar/heroicons--star.svg"),
        @image-url("../assets/sidebar/heroicons--bookmark.svg"),
    ];
    in property <[image]> down_btns: [
        @image-url("../assets/sidebar/heroicons--chart-bar.svg"),
        @image-url("../assets/sidebar/heroicons--cog-8-tooth.svg"),
    ];
}

component Btn {
    in property <image> icon;
    GridLayout {
        width: 48px;
        height: 48px;
        HorizontalLayout {
            height: parent.height;
            width: parent.width;
            Rectangle {
                height: parent.height;
                border-width: 4px;
                border-color: #ff865b;
                width: 2px;
            }

            Rectangle {
                width: 46px;
                Image {
                    source: icon;
                    width: 28px;
                    height: 28px;
                    colorize: #9FB9D0;
                }
            }
        }
    }
}

export component SideBar {
    in property <length> Height;
    width: 48px;
    Rectangle {
        background: #091319;
        width: 48px;
        height: Height;
        VerticalBox {
            padding-bottom: 0px;
            padding-top: 0px;
            alignment: space-between;
            VerticalBox {
                padding-bottom: 0px;
                padding-top: 0px;
                spacing: 0px;
                for icon in Icons.top_btns: Btn {
                    icon: icon;
                }
            }

            VerticalBox {
                padding-bottom: 0px;
                padding-top: 0px;
                spacing: 0px;
                for icon in Icons.down_btns: Btn {
                    icon: icon;
                }
            }
        }
    }
}
