[package]
name = "test_notify"
version = "0.1.0"
edition = "2021"

[dependencies]
notify = "7.0.0"
tokio = { version = "1", features = ["full"] }
crossbeam-channel = "0.5"
tracing = "0.1"
tracing-subscriber = "0.3.19"

