[workspace]
resolver = "2"
members = [
    "crates/libera-reader",
    "crates/mutool",
    "crates/gpui-kit-dynlib",
]

[workspace.dependencies]
gpui-kit = "0.7.0"
gpui = { package = "gpui-pre", version = "0.3.7" }
gpui_platform = { package = "gpui-pre-platform", version = "0.3.7", features = ["font-kit", "wayland", "x11"] }
gpui-base = { package = "gpui-base", version = "0.7.0" }
gpui-component = { package = "gpui-component", version = "0.7.0" }
gpui-component-assets = { package = "gpui-kit-assets", version = "0.7.0" }
gxhash = "3.5"
directories = "6.0.0"
notify = "8.2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
parking_lot = "0.12"
tracing = "0.1"
data-encoding = "2"
native_db = { version = "0.8.2" }
native_model = "0.4.20"
itertools = "0.14.0"
once_cell = "1"
concurrent-queue = "2.5.0"
num_cpus = "1.17.0"
tokio = { version = "1", features = ["full"] }
libc = "0.2.189"
sys-locale = "0.3.2"
anyhow = "1.0.104"
rfd = { version = "0.17.2", default-features = false, features = ["xdg-portal"] }
unicode-segmentation = "1.13.3"
tracing-subscriber = { version = "0.3", features = ["ansi"] }
reqwest = { version = "0.13", default-features = false, features = ["native-tls", "stream", "charset", "http2", "system-proxy"] }
zip = "8"
tempfile = "3"
tokio-stream = "0.1"
indicatif = "0.18.6"
image = "0.25.10"
zune-core = "0.5.3"
zune-jpegxl = "0.5.2"
jwalk = "0.8.1"
mimalloc = "0.1.52"
chrono = "0.4.45"
indexmap = { version = "2", features = ["serde"] }
colored = "3"
better-panic = "0.3"
rust-embed = "8.12.0"
rust-i18n = "3.1.5"
futures-util = { version = "0.3", features = ["sink"] }
lru = "0.18"
smallvec = "1.16"
dhat = "0.3"


[profile.dev.package]
gpui-pre = { opt-level = 3 }
gpui-component = { opt-level = 3 }
gpui-kit = { opt-level = 3 }
gpui-kit-assets = { opt-level = 3 }
gpui-pre-macros = { opt-level = 3 }
gpui-pre-platform = { opt-level = 3 }
rustybuzz = { opt-level = 3 }
taffy = { opt-level = 3 }
ttf-parser = { opt-level = 3 }
resvg = { opt-level = 3 }
smol = { opt-level = 3 }

[profile.dev.build-override]
opt-level = 0

