[workspace]
resolver = "2"
members = [
    "prisma-cli",
    "crates/libera-reader",
    "crates/libera-reader-core",
    "crates/mupdf-sys",
    "crates/mupdf", "crates/redb_example",
]
exclude = ["other"]
