[workspace]
resolver = "2"
members = [
    "crates/libera-reader-core",
    # "crates/libera-reader",
    "crates/mutool",
    "crates/utils",
]

[workspace.dependencies]
gxhash = "3.5"
directories = "6.0.0"
notify = "8.1.0"
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1"
data-encoding = "2"
native_db = { version = "0.8.2" }
native_model = "0.4.20"
itertools = "0.14.0"
once_cell = "1"
concurrent-queue = "2.5.0"
num_cpus = "1.16.0"
tokio = { version = "1", features = ["full"] }
libc = "0.2.170"
sys-locale = "0.3.2"
anyhow = "1.0.98"
gpui = "0.2.2"
rfd = "0.15.3"
unicode-segmentation = "1.12.0"
tracing-subscriber = { version = "0.3", features = ["ansi"] }
reqwest = { version = "0.12", features = ["stream"] }
zip = "4"
tempfile = "3"
tokio-stream = "0.1"
indicatif = "0.18.0"
dashmap = "6.1.0"
image = "0.25.6"
zune-core = "0.5.1"
zune-jpegxl = "0.4.0"
sysinfo = "0.37.0"
jwalk = "0.8.1"
mimalloc = { version = "0.1.48", features = ["v3"] }
chrono = "0.4.42"
indexmap = { version = "2", features = ["serde"] }
colored = "2"
