[package]
name = "mutool-bindings"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
reqwest = { workspace = true }
zip = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
libc = { workspace = true }
serde = { workspace = true }
indicatif = { workspace = true }
image = { workspace = true }
zune-core = { workspace = true }
zune-jpegxl = { workspace = true }
