[package]
name = "measure_time_macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = { version = "2.0.95", features = ["full"] }
tracing = "0.1.40"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
tracing-subscriber = "0.3.18"
