[package]
name = "utils"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
data-encoding = { workspace = true }
tracing-subscriber = { workspace = true }
gxhash = { workspace = true }
concurrent-queue = { workspace = true }
colored = { workspace = true }
