[package]
name = "libera-reader"
version = "0.1.0"
authors = ["RikaKit2"]
license = "AGPL-3"
repository = "https://github.com/RikaKit2/libera-reader"
edition = "2024"

[features]
default = []
dhat-heap = ["dep:dhat"]

[dependencies]
gpui = { workspace = true }
gpui_platform = { workspace = true }
gpui-component = { workspace = true }
rfd = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
unicode-segmentation = { workspace = true }
libera-reader-core = { version = "0.0.2", path = "../libera-reader-core" }
mutool = { version = "0.1.0", path = "../mutool" }
utils = { version = "0.1.0", path = "../utils" }
mimalloc = { workspace = true }
better-panic = { workspace = true }
tracing = { workspace = true }
gpui-component-assets = { workspace = true }
rust-embed = { workspace = true }
rust-i18n = { workspace = true }
tokio = { workspace = true }
futures-util = { workspace = true }
lru = { workspace = true }
libc = { workspace = true }
image = { workspace = true }
smallvec = { workspace = true }
dhat = { workspace = true, optional = true }
