[package]
name = "libera-reader"
version = "0.1.0"
authors = ["RikaKit2"]
license = "AGPL-3"
repository = "https://github.com/RikaKit2/libera-reader"
edition = "2024"

[profile.dev]
opt-level = 1

[profile.release]
codegen-units = 1
lto = true

[dependencies]
gpui = { workspace = true }
rfd = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
unicode-segmentation = { workspace = true }
libera-reader-core = { version = "0.0.2", path = "../libera-reader-core" }
utils = { version = "0.1.0", path = "../utils" }
mimalloc = { workspace = true }
