cargo-features = ["codegen-backend"]

[toolchain]
channel = "nightly"

[unstable]
codegen-backend = true

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold", "-Zshare-generics=y"]

[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"

[profile.dev]
codegen-backend = "cranelift"
opt-level = 1

[profile.release]
codegen-units = 1
lto = true

[build]
rustflags = ["-C", "target-cpu=native"]
