[env]
RUSTC_BOOTSTRAP = "1"

[build]
rustflags = ["-C", "target-cpu=native"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-cpu=native", "-C", "link-arg=--ld-path=wild", "-C", "prefer-dynamic", "-Zshare-generics=y"]

[alias]
run-dev = "run --package libera-reader --features dev"
build-dev = "build --package libera-reader --features dev"

[profile.dev]
codegen-units = 16
lto = false
panic = "unwind"
strip = "none"
debug = "line-tables-only"
split-debuginfo = "unpacked"
opt-level = 1
incremental = true

[profile.dev.package."*"]
opt-level = 2

[profile.dev.package.gxhash]
opt-level = 2

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"
strip = "symbols"
debug = false
opt-level = 3
