[build]
rustflags = ["-Ctarget-cpu=native"]

[profile.dev]
opt-level = 1

[profile.release]
codegen-units = 1
opt-level = 3
lto = true
strip = true


[target.x86_64-unknown-linux-gnu]
rustflags = ["-Clink-arg=-fuse-ld=mold", "-Ctarget-cpu=native"]
