import { HorizontalBox } from "std-widgets.slint";
import { SideBar } from "side_bar.slint";
import { Content } from "content/content.slint";
import { Header } from "header.slint";
import {Rotes} from "../../vars.slint";

export component App {
    in property <length> Height;
    in property <length> Width;
    height: Height;
    width: Width;
    HorizontalBox {
        spacing: 0px;
        padding: 0px;
        side_bar := SideBar { }

        Content {
            Height: root.height;
            Width: root.width;
        }
    }
}
