import { Global } from "../../vars.slint";
import { SideBar } from "side_bar.slint";
import { Header } from "header.slint";


export component Main {
    height: 100%;
    width: 100%;
    Rectangle {
        height: 100%;
        width: 100%;
        background: Global.curr_theme.bg-100;
        HorizontalLayout {
            SideBar {
                width: 48px;
            }

            Header { }
        }
    }
}
