[package]
name = "libera-reader-core"
version = "0.0.1"
authors = ["RikaKit2"]
license = "AGPL-3"
repository = "https://github.com/RikaKit2/libera-reader"
edition = "2021"

[dependencies]
blake3 = "1.5.1"
crossbeam-channel = "0.5.13"
directories = "5.0.1"
globset = "0.4.14"
notify = "6.1.1"
prisma-client-rust = { git = "https://github.com/Brendonovich/prisma-client-rust", tag = "0.6.11", default-features = false, features = ["sqlite", "migrations", "mocking", "specta"] }
serde = "1.0.203"
tokio = { version = "1.38.0", features = ["rt", "rt-multi-thread", "macros", "tracing"] }
tracing = "0.1.40"
once_cell = "1.19.0"

[dev-dependencies]
tracing-subscriber = "0.3.18"
