[package]
name = "libera-reader-core"
version = "0.0.2"
authors = ["RikaKit2"]
license = "AGPL-3"
repository = "https://github.com/RikaKit2/libera-reader"
edition = "2024"

[dependencies]
gxhash = { workspace = true }
directories = { workspace = true }
notify = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
walkdir = { workspace = true }
rayon = { workspace = true }
native_db = { workspace = true }
native_model = { workspace = true }
itertools = { workspace = true }
once_cell = { workspace = true }
concurrent-queue = { workspace = true }
num_cpus = { workspace = true }
tokio = { workspace = true }
libc = { workspace = true }
sys-locale = { workspace = true }
anyhow = { workspace = true }
gpui = { workspace = true }
measure_time_macro = { version = "0.1.0", path = "../measure_time_macro" }
utils = { version = "0.1.0", path = "../utils" }

